// Samples — what the demo shows and sends, read from the assets directory's demo/ (written by make_samples.py):
// samples.json (the inbox, the order log, the words the screen uses for every question and answer), requests/<id>.json
// (each item's System One request, sent to the model as it is on disk), pictures/*.png. Nothing here is generated by
// the app: an answer on screen is the model's response, mapped to words by `display`.

import CoreGraphics
import D1
import Foundation
import ImageIO

struct Samples: Decodable {
    struct Item: Decodable, Identifiable {
        let id: String
        let kind: String
        let text: String
        let picture: String?
        let questions: [String]
    }

    struct Log: Decodable {
        let id: String
        let title: String
        let entries: Int
        let questions: [String]
    }

    struct Display: Decodable {
        let label: String
        let yes: String?
        let no: String?
        let chip_yes: String?
        let chip_no: String?
        let options: [String: String]?
        let levels: [String]?
        let chips: Chips?
    }

    /// `chips`: a list for a score's levels, an object for a choice's options.
    enum Chips: Decodable {
        case levels([String])
        case options([String: String])

        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let a = try? c.decode([String].self) { self = .levels(a) } else { self = .options(try c.decode([String: String].self)) }
        }
    }

    let inbox: [Item]
    let log: Log
    let display: [String: Display]
    let warmup: [String]
    let requests: [String: String]
}

/// One question's answer as the screen shows it, from the response body.
struct Answer: Equatable, Sendable {
    let question: String
    /// the option the response picked: noul "yes" / "no", a choice's key, a score's level "k"
    let option: String
    /// the words for it (`display`)
    let text: String
    let chip: String
    /// its probability
    let p: Double
}

/// A loaded sample set: the parsed samples.json, each request's bytes and picture files, the log's entries.
struct DemoSet {
    let root: URL
    let samples: Samples
    let requests: [String: Data]
    let pictures: [String: [URL]]
    let images: [String: CGImage]
    let logEntries: [String]
    /// each choice question's option keys in the request's order
    let questionOrder: [String: [String]]

    init(root: URL) throws {
        self.root = root
        samples = try JSONDecoder().decode(Samples.self, from: Data(contentsOf: root.appending(path: "samples.json")))
        var reqs: [String: Data] = [:]
        var pics: [String: [URL]] = [:]
        for (id, rel) in samples.requests {
            let url = root.appending(path: rel)
            let data = try Data(contentsOf: url)
            reqs[id] = data
            // the request's own "images": files relative to the request's folder (decide.py's rule)
            let files = try JSONParser.parse(data)["images"]?.array?.compactMap(\.string) ?? []
            pics[id] = files.map { url.deletingLastPathComponent().appending(path: $0).standardizedFileURL }
        }
        requests = reqs
        pictures = pics
        var ims: [String: CGImage] = [:]
        for item in samples.inbox {
            guard let rel = item.picture else { continue }
            let url = root.appending(path: rel)
            guard let src = CGImageSourceCreateWithURL(url as CFURL, nil),
                  let im = CGImageSourceCreateImageAtIndex(src, 0, nil)
            else { throw DemoError.sample("cannot read \(rel)") }
            ims[item.id] = im
        }
        images = ims
        logEntries = try Self.entries(reqs[samples.log.id] ?? Data())
        var order: [String: [String]] = [:]
        for data in reqs.values {
            guard let qs = try JSONParser.parse(data)["questions"]?.members else { continue }
            for q in qs { if let c = q.value["criteria"]?.members { order[q.key] = c.map(\.key) } }
        }
        questionOrder = order
    }

    func display(_ q: String) -> Samples.Display? { samples.display[q] }

    /// The options a question offers, as the screen words them, for a row still waiting for its answer.
    func optionsHint(_ q: String) -> String? {
        guard let d = display(q) else { return nil }
        if let yes = d.yes, let no = d.no { return "\(yes) / \(no)" }
        if let levels = d.levels { return levels.joined(separator: " · ") }
        if let options = d.options, let order = questionOrder[q] { return order.compactMap { options[$0] }.joined(separator: " · ") }
        return nil
    }

    /// The response's answers, in the request's order, as the screen words them.
    func answers(_ body: JSONValue, questions: [String]) throws -> [Answer] {
        guard let all = body["answers"] else { throw DemoError.sample("no answers in the response") }
        return try questions.map { name in
            guard let a = all[name], let type = a["type"]?.string else { throw DemoError.sample("no answer for \(name)") }
            let d = display(name)
            switch type {
            case "noul":
                guard let yes = a["noul"]?.double else { throw DemoError.sample("\(name): no noul p") }
                let pick = yes >= 1 - yes
                return Answer(question: name, option: pick ? "yes" : "no",
                              text: (pick ? d?.yes : d?.no) ?? (pick ? "Yes" : "No"),
                              chip: (pick ? d?.chip_yes : d?.chip_no) ?? (pick ? "Yes" : "No"), p: pick ? yes : 1 - yes)
            case "choice":
                guard let key = a["choice"]?.string, let p = a["confidence"]?.double else {
                    throw DemoError.sample("\(name): no choice")
                }
                var chip = d?.options?[key] ?? key
                if case .options(let m)? = d?.chips, let c = m[key] { chip = c }
                return Answer(question: name, option: key, text: d?.options?[key] ?? key, chip: chip, p: p)
            case "score":
                guard let probs = a["probabilities"]?.members, !probs.isEmpty else { throw DemoError.sample("\(name): no p") }
                // the first level with the highest p (Python's max over the list in order)
                var best = 0
                for (k, m) in probs.enumerated() where (m.value.double ?? 0) > (probs[best].value.double ?? 0) { best = k }
                let p = probs[best].value.double ?? 0
                let level = Int(probs[best].key) ?? best
                let text = d?.levels.flatMap { level < $0.count ? $0[level] : nil } ?? probs[best].key
                var chip = text
                if case .levels(let l)? = d?.chips, level < l.count { chip = l[level] }
                return Answer(question: name, option: probs[best].key, text: text, chip: chip, p: p)
            default:
                throw DemoError.sample("\(name): type \(type)")
            }
        }
    }

    /// The order log's events as one line each: time, action, order, amount, who; approvals and reasons after.
    static func entries(_ request: Data) throws -> [String] {
        guard let state = try JSONParser.parse(request)["state"]?.array else { return [] }
        return state.map { e in
            let time = (e["time"]?.string ?? "").split(separator: " ").last.map(String.init) ?? ""
            let action = (e["action"]?.string ?? "").padding(toLength: 6, withPad: " ", startingAt: 0)
            let order = (e["order"]?.string ?? "").replacingOccurrences(of: "order ", with: "#")
            let amount = e["amount"].flatMap { $0.double }.map { String(format: "%7.2f", $0) } ?? ""
            let who = (e["actor"]?.string ?? "").replacingOccurrences(of: "the ", with: "")
            var line = "\(time)  \(action)  \(order)  \(amount)  \(who)"
            if let by = e["approved_by"]?.string { line += " · approved: " + by.replacingOccurrences(of: "the ", with: "") }
            if let why = e["reason"]?.string { line += " · " + why }
            return line
        }
    }
}

enum DemoError: Error, CustomStringConvertible {
    case sample(String)
    case assets(String)

    var description: String {
        switch self {
        case .sample(let s): return "samples: \(s)"
        case .assets(let s): return "assets: \(s)"
        }
    }
}
