#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "pillow>=11",
# ]
# [tool.uv]
# index-url = "https://pypi.org/simple"
# ///
"""Fixture images + row definitions for the decider-2b-vision oracle, drawn from nothing.

Every image is generated here with Pillow's drawing primitives (rectangles, ellipses, polygons);
no photo, font file or downloaded asset is involved, so the fixture can be published under
CC0-1.0. Digits are seven-segment polygons, not glyphs. No real people, companies or products
appear in the pictures or in the text this file defines. The game-frame contexts are the
author's training prompts (`decider/games/envs.py` `intro` + `decider/games/frames_data.py`
VIS_INTRO), kept word for word except that the two game titles and their maker's name are
replaced by a plain description ("a two-paddle ball game", "a brick-breaking game").

The rows follow three input shapes the checkpoint was trained or benchmarked on:

* the author's MPS bench case (`decider/bench/mps.py`): a solid 224x224 `Image.new("RGB",
  (224, 224), color)` with "Identify the dominant color in the image." and
  `Q("What color is shown?", ["red", "green", "blue"])`;
* The Cauldron form (`decider/vision/data.py`): context "This is a visual question about the
  image.", one or more lettered questions;
* the game-frame form (`decider/games/frames_data.py`): `f"{intro} The image shows the current
  game screen."` + "What should you do right now?" with the game's own option list;

plus text-only rows (no image), the decider's text readout through the same model.

    python3 conversion/decider_vision/make_fixture_images.py            # -> $ZOO_WORK_ROOT/_decider2bv/fixtures
    python3 conversion/decider_vision/make_fixture_images.py --out-dir /tmp/fx

Writes `images/<name>.png`, `meta.json` (size, PNG and raw-RGB sha256, the generator and its
arguments, licence) and `rows.json` (context, questions, options, the intended answer). The
drawing is deterministic: re-running reproduces the raw-RGB sha256 exactly (the PNG bytes
depend on the zlib build, the pixels do not).
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
import os
import sys
from pathlib import Path

from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _paths import work_path  # noqa: E402

LICENSE = "self-made (generated by make_fixture_images.py), CC0-1.0"
IMG_CONTEXT = "This is a visual question about the image."
VIS_INTRO = "The image shows the current game screen."
GAME_QUESTION = "What should you do right now?"

# decider/games/envs.py @ Mapika/decider origin/main 23579f7 (Apache-2.0): options and the MiniGrid /
# CliffWalking intros verbatim; in the two paddle-game intros only the title and maker are replaced.
PONG_INTRO = ("You play a two-paddle ball game and control the right paddle. Move the paddle so the ball hits it; "
              "the ball bounces off paddles and walls. Missing the ball loses a point.")
PONG_OPTIONS = ["move paddle up", "move paddle down", "stay"]
BREAKOUT_INTRO = ("You play a brick-breaking game: move the paddle at the bottom so the ball bounces up into the "
                  "bricks. Missing the ball loses a life.")
BREAKOUT_OPTIONS = ["move paddle left", "move paddle right", "stay", "launch ball"]
MINIGRID_EMPTY_INTRO = ("You control an agent in a grid world seen from its own viewpoint (7x7 cells ahead and "
                        "to the sides). Reach the green goal square. 'move forward' moves one cell; turning "
                        "changes facing.")
MINIGRID_OPTIONS = ["turn left", "turn right", "move forward", "pick up", "drop", "toggle (open door / use)"]
CLIFF_INTRO = ("You walk on a 4x12 grid from the bottom-left start to the bottom-right goal. The bottom row "
               "between them is a cliff: stepping on it sends you back to the start with a big penalty. "
               "Every step costs 1.")
CLIFF_OPTIONS = ["move up", "move right", "move down", "move left"]

# Seven-segment layout: a top, b upper right, c lower right, d bottom, e lower left, f upper left, g middle.
SEGMENTS = {"0": "abcdef", "1": "bc", "2": "abged", "3": "abgcd", "4": "fgbc",
            "5": "afgcd", "6": "afgecd", "7": "abc", "8": "abcdefg", "9": "abcdfg"}


# --------------------------------------------------------------------------- drawing helpers
def _hseg(d, x1, x2, y, t, fill):
    h = t / 2
    d.polygon([(x1, y), (x1 + h, y - h), (x2 - h, y - h), (x2, y), (x2 - h, y + h), (x1 + h, y + h)], fill=fill)


def _vseg(d, x, y1, y2, t, fill):
    h = t / 2
    d.polygon([(x, y1), (x + h, y1 + h), (x + h, y2 - h), (x, y2), (x - h, y2 - h), (x - h, y1 + h)], fill=fill)


def seven_segment(d, digit, x0, y0, w, h, t, fill, gap=2):
    on = SEGMENTS[digit]
    xl, xr = x0 + t / 2, x0 + w - t / 2
    yt, ym, yb = y0 + t / 2, y0 + h / 2, y0 + h - t / 2
    if "a" in on: _hseg(d, xl + gap, xr - gap, yt, t, fill)
    if "g" in on: _hseg(d, xl + gap, xr - gap, ym, t, fill)
    if "d" in on: _hseg(d, xl + gap, xr - gap, yb, t, fill)
    if "f" in on: _vseg(d, xl, yt + gap, ym - gap, t, fill)
    if "b" in on: _vseg(d, xr, yt + gap, ym - gap, t, fill)
    if "e" in on: _vseg(d, xl, ym + gap, yb - gap, t, fill)
    if "c" in on: _vseg(d, xr, ym + gap, yb - gap, t, fill)


def star_points(cx, cy, r_out, r_in, n=5):
    pts = []
    for k in range(2 * n):
        r = r_out if k % 2 == 0 else r_in
        a = -math.pi / 2 + k * math.pi / n
        pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    return pts


def canvas(w, h, bg):
    im = Image.new("RGB", (w, h), bg)
    return im, ImageDraw.Draw(im)


# --------------------------------------------------------------------------- the images
def author_color(color):
    # Exactly decider/bench/mps.py: Image.new("RGB", (224, 224), color). PIL "green" is (0, 128, 0).
    return Image.new("RGB", (224, 224), color)


def circle_red_256():
    im, d = canvas(256, 256, "white")
    d.ellipse([48, 48, 208, 208], fill=(220, 30, 30))
    return im


def square_blue_320x240():
    im, d = canvas(320, 240, "white")
    d.rectangle([90, 50, 230, 190], fill=(30, 60, 220))
    return im


def triangle_green_240x320():
    im, d = canvas(240, 320, "white")
    d.polygon([(120, 70), (40, 250), (200, 250)], fill=(30, 160, 60))
    return im


def star_yellow_640x360():
    im, d = canvas(640, 360, (40, 40, 48))
    d.polygon(star_points(320, 185, 130, 52), fill=(250, 210, 30))
    return im


def dots_three_256():
    im, d = canvas(256, 256, "white")
    for x in (64, 128, 192):
        d.ellipse([x - 22, 128 - 22, x + 22, 128 + 22], fill=(0, 0, 0))
    return im


def dots_five_320x240():
    im, d = canvas(320, 240, "white")
    for x, y in ((100, 60), (220, 60), (160, 120), (100, 180), (220, 180)):
        d.ellipse([x - 18, y - 18, x + 18, y + 18], fill=(220, 30, 30))
    return im


def ball_left_640x360():
    im, d = canvas(640, 360, (200, 200, 200))
    d.ellipse([110 - 40, 180 - 40, 110 + 40, 180 + 40], fill=(220, 30, 30))
    return im


def stripes_vertical_256():
    im, d = canvas(256, 256, "white")
    for k in range(0, 8, 2):
        d.rectangle([k * 32, 0, k * 32 + 31, 255], fill=(0, 0, 0))
    return im


def checker_320x240():
    im, d = canvas(320, 240, "white")
    for r in range(6):
        for c in range(8):
            if (r + c) % 2 == 0:
                d.rectangle([c * 40, r * 40, c * 40 + 39, r * 40 + 39], fill=(0, 0, 0))
    return im


def grid_cell_256():
    im, d = canvas(256, 256, "white")
    d.rectangle([160, 160, 224, 224], fill=(220, 30, 30))
    for v in (32, 96, 160, 224):
        d.line([(v, 32), (v, 224)], fill=(0, 0, 0), width=4)
        d.line([(32, v), (224, v)], fill=(0, 0, 0), width=4)
    return im


def arrow_up_256():
    im, d = canvas(256, 256, "white")
    d.rectangle([108, 110, 148, 220], fill=(0, 0, 0))
    d.polygon([(128, 36), (64, 120), (192, 120)], fill=(0, 0, 0))
    return im


def arrow_left_640x360():
    im, d = canvas(640, 360, "white")
    d.rectangle([210, 150, 520, 210], fill=(0, 0, 0))
    d.polygon([(120, 180), (220, 90), (220, 270)], fill=(0, 0, 0))
    return im


def bars_320x240():
    im, d = canvas(320, 240, "white")
    base = 215
    for k, h in enumerate((80, 120, 170, 60)):
        x = 40 + 70 * k
        d.rectangle([x, base - h, x + 40, base], fill=(70, 110, 200))
    d.line([(30, base), (300, base)], fill=(0, 0, 0), width=3)
    d.line([(30, 20), (30, base)], fill=(0, 0, 0), width=3)
    return im


def lamp_top_240x320():
    im, d = canvas(240, 320, (230, 230, 230))
    d.rectangle([80, 30, 160, 290], fill=(40, 40, 40))
    for k, cy in enumerate((75, 160, 245)):
        d.ellipse([120 - 28, cy - 28, 120 + 28, cy + 28], fill=(240, 30, 30) if k == 0 else (70, 70, 70))
    return im


def bands_640x360():
    im, d = canvas(640, 360, "white")
    colors = [(220, 30, 30), (245, 140, 20), (245, 220, 30), (30, 160, 60), (30, 60, 220)]
    for k, col in enumerate(colors):
        d.rectangle([k * 128, 0, k * 128 + 127, 359], fill=col)
    return im


def two_shapes_640x360():
    im, d = canvas(640, 360, "white")
    d.ellipse([180 - 90, 180 - 90, 180 + 90, 180 + 90], fill=(30, 60, 220))
    d.rectangle([460 - 85, 180 - 85, 460 + 85, 180 + 85], fill=(245, 140, 20))
    return im


def seg_7_256():
    im, d = canvas(256, 256, "white")
    seven_segment(d, "7", 78, 38, 100, 180, 18, (0, 0, 0))
    return im


def seg_3_320x240():
    im, d = canvas(320, 240, (0, 0, 0))
    seven_segment(d, "3", 110, 30, 100, 180, 18, (240, 40, 40))
    return im


def seg_42_640x360():
    im, d = canvas(640, 360, "white")
    seven_segment(d, "4", 180, 70, 120, 220, 22, (20, 40, 120))
    seven_segment(d, "2", 340, 70, 120, 220, 22, (20, 40, 120))
    return im


# Game frames, 256x240. Simple rectangles in the colour scheme of the emulator frames the model
# was trained on; the layouts are drawn here and follow each game's scripted teacher in envs.py.
PONG_BG, PONG_WALL, PONG_OPP, PONG_ME = (144, 72, 17), (236, 236, 236), (213, 130, 74), (92, 186, 92)


def _pong(me_center_y, ball_xy):
    im, d = canvas(256, 240, PONG_BG)
    d.rectangle([0, 24, 255, 33], fill=PONG_WALL)
    d.rectangle([0, 216, 255, 225], fill=PONG_WALL)
    seven_segment(d, "0", 52, 4, 10, 16, 3, PONG_OPP, gap=1)
    seven_segment(d, "0", 190, 4, 10, 16, 3, PONG_ME, gap=1)
    d.rectangle([20, 110, 25, 133], fill=PONG_OPP)                       # opponent (left)
    d.rectangle([230, me_center_y - 12, 235, me_center_y + 11], fill=PONG_ME)  # you (right)
    bx, by = ball_xy
    d.rectangle([bx - 2, by - 3, bx + 1, by + 2], fill=PONG_WALL)
    return im


def pong_up_256x240():      # ball 90 px above the paddle centre -> teacher: "move paddle up"
    return _pong(170, (200, 80))


def pong_down_256x240():    # ball 110 px below the paddle centre -> "move paddle down"
    return _pong(70, (190, 180))


def pong_stay_256x240():    # ball level with the paddle centre -> "stay"
    return _pong(120, (200, 120))


BRICKS = [(200, 72, 72), (198, 108, 58), (180, 122, 48), (162, 162, 42), (72, 160, 72), (66, 72, 200)]


def _breakout(paddle_center_x, ball_xy):
    im, d = canvas(256, 240, (0, 0, 0))
    wall = (142, 142, 142)
    d.rectangle([0, 16, 255, 27], fill=wall)
    d.rectangle([0, 16, 7, 239], fill=wall)
    d.rectangle([248, 16, 255, 239], fill=wall)
    for r, col in enumerate(BRICKS):
        y = 50 + 6 * r
        for c in range(16):
            x = 8 + 15 * c
            d.rectangle([x, y, x + 14, y + 5], fill=col)
    d.rectangle([paddle_center_x - 8, 220, paddle_center_x + 7, 223], fill=BRICKS[0])
    if ball_xy is not None:
        bx, by = ball_xy
        d.rectangle([bx - 2, by - 2, bx + 1, by + 1], fill=BRICKS[0])
    return im


def breakout_left_256x240():    # ball 120 px left of the paddle -> "move paddle left"
    return _breakout(190, (70, 160))


def breakout_launch_256x240():  # no ball in play -> "launch ball"
    return _breakout(128, None)


def minigrid_forward_256x240():
    # An 8x8 MiniGrid-Empty-style room, 30 px tiles: grey walls, black floor, green goal at (6,6),
    # red agent at (3,6) facing east with the goal straight ahead -> "move forward". Cells in the
    # agent's view are lightened as the environment's renderer highlights them.
    im, d = canvas(256, 240, (0, 0, 0))
    t, ox = 30, 8
    agent, goal = (3, 6), (6, 6)

    def lit(col):
        return tuple(int(v + (255 - v) * 0.3) for v in col)

    for y in range(8):
        for x in range(8):
            wall = x in (0, 7) or y in (0, 7)
            col = (100, 100, 100) if wall else (0, 0, 0)
            if (x, y) == goal:
                col = (0, 255, 0)
            if 3 <= x <= 7 and 3 <= y <= 7:           # the 7x7 egocentric view, clipped to the room
                col = lit(col)
            x0, y0 = ox + x * t, y * t
            d.rectangle([x0, y0, x0 + t - 1, y0 + t - 1], fill=col)
            d.line([(x0, y0), (x0 + t - 1, y0)], fill=(100, 100, 100))
            d.line([(x0, y0), (x0, y0 + t - 1)], fill=(100, 100, 100))
    ax, ay = ox + agent[0] * t, agent[1] * t
    d.polygon([(ax + 0.12 * t, ay + 0.19 * t), (ax + 0.87 * t, ay + 0.50 * t), (ax + 0.12 * t, ay + 0.81 * t)],
              fill=(255, 0, 0))
    return im


def cliff_up_256x240():
    # A 4x12 walk grid, 20 px cells: the cliff (row 3, columns 1-10) dark, the goal (3,11) green,
    # the walker (blue disc) on the start cell (3,0) -> teacher: "move up".
    im, d = canvas(256, 240, (120, 170, 220))
    t, ox, oy = 20, 8, 80
    for r in range(4):
        for c in range(12):
            col = (225, 225, 215)
            if r == 3 and 1 <= c <= 10:
                col = (90, 60, 40)
            if (r, c) == (3, 11):
                col = (40, 180, 60)
            x0, y0 = ox + c * t, oy + r * t
            d.rectangle([x0, y0, x0 + t - 1, y0 + t - 1], fill=col, outline=(60, 60, 60))
    cx, cy = ox + 0 * t + t // 2, oy + 3 * t + t // 2
    d.ellipse([cx - 7, cy - 7, cx + 7, cy + 7], fill=(30, 60, 220))
    return im


IMAGES = {
    "mps_red": (author_color, {"color": "red"}),
    "mps_green": (author_color, {"color": "green"}),
    "mps_blue": (author_color, {"color": "blue"}),
    "circle_red_256": (circle_red_256, {}),
    "square_blue_320x240": (square_blue_320x240, {}),
    "triangle_green_240x320": (triangle_green_240x320, {}),
    "star_yellow_640x360": (star_yellow_640x360, {}),
    "dots_three_256": (dots_three_256, {}),
    "dots_five_320x240": (dots_five_320x240, {}),
    "ball_left_640x360": (ball_left_640x360, {}),
    "stripes_vertical_256": (stripes_vertical_256, {}),
    "checker_320x240": (checker_320x240, {}),
    "grid_cell_256": (grid_cell_256, {}),
    "arrow_up_256": (arrow_up_256, {}),
    "arrow_left_640x360": (arrow_left_640x360, {}),
    "bars_320x240": (bars_320x240, {}),
    "lamp_top_240x320": (lamp_top_240x320, {}),
    "bands_640x360": (bands_640x360, {}),
    "two_shapes_640x360": (two_shapes_640x360, {}),
    "seg_7_256": (seg_7_256, {}),
    "seg_3_320x240": (seg_3_320x240, {}),
    "seg_42_640x360": (seg_42_640x360, {}),
    "pong_up_256x240": (pong_up_256x240, {}),
    "pong_down_256x240": (pong_down_256x240, {}),
    "pong_stay_256x240": (pong_stay_256x240, {}),
    "breakout_left_256x240": (breakout_left_256x240, {}),
    "breakout_launch_256x240": (breakout_launch_256x240, {}),
    "minigrid_forward_256x240": (minigrid_forward_256x240, {}),
    "cliff_up_256x240": (cliff_up_256x240, {}),
}


# --------------------------------------------------------------------------- the rows
def q(text, options, gold):
    assert 2 <= len(options) <= 10 and 0 <= gold < len(options), (text, options, gold)
    return {"text": text, "options": list(options), "gold": gold}


def row(id, image, context, questions, form):
    return {"id": id, "image": image, "context": context, "questions": questions, "form": form}


DIGITS = [str(k) for k in range(10)]
COUNTS8 = ["one", "two", "three", "four", "five", "six", "seven", "eight"]
CELLS = ["top left", "top center", "top right", "middle left", "center", "middle right",
         "bottom left", "bottom center", "bottom right"]
COLORS6 = ["red", "orange", "yellow", "green", "blue", "purple"]
NO_YES = ["no", "yes"]

ROWS = [
    # the author's MPS bench case, exactly
    row("r01", "mps_red", "Identify the dominant color in the image.", [q("What color is shown?", ["red", "green", "blue"], 0)], "author_mps"),
    row("r02", "mps_green", "Identify the dominant color in the image.", [q("What color is shown?", ["red", "green", "blue"], 1)], "author_mps"),
    row("r03", "mps_blue", "Identify the dominant color in the image.", [q("What color is shown?", ["red", "green", "blue"], 2)], "author_mps"),
    # shapes, colours, counts, positions (The Cauldron form)
    row("r04", "circle_red_256", IMG_CONTEXT, [q("What shape is shown?", ["circle", "square", "triangle", "star"], 0),
                                              q("What color is the shape?", ["red", "green", "blue", "yellow", "purple"], 0)], "cauldron"),
    row("r05", "square_blue_320x240", IMG_CONTEXT, [q("What shape is shown?", ["circle", "square", "triangle"], 1)], "cauldron"),
    row("r06", "triangle_green_240x320", IMG_CONTEXT, [q("What shape is shown?", ["circle", "square", "triangle", "star", "hexagon", "oval", "diamond", "heart"], 2)], "cauldron"),
    row("r07", "star_yellow_640x360", IMG_CONTEXT, [q("What shape is shown?", ["star", "circle", "square", "triangle"], 0),
                                                   q("What color is the shape?", ["red", "yellow", "blue", "green", "black", "white"], 1),
                                                   q("Is the background dark?", NO_YES, 1)], "cauldron"),
    row("r08", "dots_three_256", IMG_CONTEXT, [q("How many dots are in the image?", COUNTS8[:6], 2)], "cauldron"),
    row("r09", "dots_five_320x240", IMG_CONTEXT, [q("How many dots are in the image?", COUNTS8, 4)], "cauldron"),
    row("r10", "ball_left_640x360", IMG_CONTEXT, [q("Where is the red ball?", ["on the left", "in the center", "on the right"], 0)], "cauldron"),
    row("r11", "stripes_vertical_256", IMG_CONTEXT, [q("Are the stripes horizontal or vertical?", ["horizontal", "vertical"], 1)], "cauldron"),
    row("r12", "checker_320x240", IMG_CONTEXT, [q("What pattern is shown?", ["checkerboard", "stripes", "polka dots", "solid color", "gradient"], 0)], "cauldron"),
    row("r13", "grid_cell_256", IMG_CONTEXT, [q("Which cell of the grid is filled?", CELLS, 8)], "cauldron"),
    row("r14", "arrow_up_256", IMG_CONTEXT, [q("Which direction does the arrow point?", ["up", "down", "left", "right"], 0)], "cauldron"),
    row("r15", "arrow_left_640x360", IMG_CONTEXT, [q("Which direction does the arrow point?", ["right", "up", "left", "down"], 2),
                                                  q("What color is the arrow?", ["black", "white", "red"], 0)], "cauldron"),
    row("r16", "bars_320x240", IMG_CONTEXT, [q("Which bar is the tallest?", ["the first", "the second", "the third", "the fourth"], 2),
                                            q("How many bars are there?", COUNTS8[1:], 2),
                                            q("Are the bars vertical?", NO_YES, 1)], "cauldron"),
    row("r17", "lamp_top_240x320", IMG_CONTEXT, [q("Which lamp is lit?", ["top", "middle", "bottom"], 0),
                                                q("What color is the lit lamp?", ["red", "yellow", "green"], 0),
                                                q("Should a driver stop or go?", ["stop", "go"], 0)], "cauldron"),
    row("r18", "bands_640x360", IMG_CONTEXT, [q("What color is the leftmost band?", COLORS6, 0),
                                             q("How many color bands are there?", COUNTS8[2:7], 2),
                                             q("What color is the rightmost band?", COLORS6, 4)], "cauldron"),
    row("r19", "two_shapes_640x360", IMG_CONTEXT, [q("What shape is on the left?", ["circle", "square", "triangle"], 0),
                                                  q("What color is the square?", ["red", "orange", "blue", "green"], 1),
                                                  q("Is there a triangle in the image?", NO_YES, 0)], "cauldron"),
    # seven-segment digits (all ten letters A-J in play)
    row("r20", "seg_7_256", IMG_CONTEXT, [q("What digit is shown?", DIGITS, 7)], "cauldron"),
    row("r21", "seg_3_320x240", IMG_CONTEXT, [q("What digit is shown?", DIGITS, 3)], "cauldron"),
    row("r22", "seg_42_640x360", IMG_CONTEXT, [q("What number is shown?", ["12", "24", "40", "42", "45", "47", "52", "72", "74"], 3)], "cauldron"),
    # game frames in the training form
    row("r23", "pong_up_256x240", f"{PONG_INTRO} {VIS_INTRO}", [q(GAME_QUESTION, PONG_OPTIONS, 0)], "game_frame"),
    row("r24", "pong_down_256x240", f"{PONG_INTRO} {VIS_INTRO}", [q(GAME_QUESTION, PONG_OPTIONS, 1)], "game_frame"),
    row("r25", "pong_stay_256x240", f"{PONG_INTRO} {VIS_INTRO}", [q(GAME_QUESTION, PONG_OPTIONS, 2)], "game_frame"),
    row("r26", "breakout_left_256x240", f"{BREAKOUT_INTRO} {VIS_INTRO}", [q(GAME_QUESTION, BREAKOUT_OPTIONS, 0)], "game_frame"),
    row("r27", "breakout_launch_256x240", f"{BREAKOUT_INTRO} {VIS_INTRO}", [q(GAME_QUESTION, BREAKOUT_OPTIONS, 3)], "game_frame"),
    row("r28", "minigrid_forward_256x240", f"{MINIGRID_EMPTY_INTRO} {VIS_INTRO}", [q(GAME_QUESTION, MINIGRID_OPTIONS, 2)], "game_frame"),
    row("r29", "cliff_up_256x240", f"{CLIFF_INTRO} {VIS_INTRO}", [q(GAME_QUESTION, CLIFF_OPTIONS, 0)], "game_frame"),
    # second questions on images already used above
    row("r30", "circle_red_256", IMG_CONTEXT, [q("What is the main object in the image?", ["a red circle", "a blue square", "a green triangle", "a yellow star"], 0)], "cauldron"),
    row("r31", "bars_320x240", IMG_CONTEXT, [q("Which bar is the shortest?", ["the first", "the second", "the third", "the fourth"], 3)], "cauldron"),
    row("r32", "grid_cell_256", IMG_CONTEXT, [q("Is the filled cell in the bottom row?", NO_YES, 1)], "cauldron"),
    row("r33", "seg_3_320x240", IMG_CONTEXT, [q("What color are the lit segments?", ["black", "red", "green", "blue"], 1),
                                             q("Is the digit even or odd?", ["even", "odd"], 1)], "cauldron"),
    row("r34", "mps_red", "Identify the dominant color in the image.", [q("What color is shown?", ["red", "orange", "yellow", "green", "blue", "purple", "black"], 0)], "author_mps"),
    row("r35", "dots_five_320x240", IMG_CONTEXT, [q("What color are the dots?", ["black", "red", "blue", "green"], 1),
                                                 q("Are the dots arranged in a single row?", NO_YES, 0)], "cauldron"),
    # text-only rows (no image): the decider text readout through the same model
    row("t01", None, "A delivery box arrived with a torn corner. The items inside are undamaged. The customer wants a replacement box, not a refund.",
        [q("What does the customer want?", ["a refund", "a replacement box", "a discount"], 1)], "text"),
    row("t02", None, "The kitchen light is on and the window is open. It is raining outside.",
        [q("Is the window open?", NO_YES, 1), q("Is it raining?", NO_YES, 1), q("Which light is on?", ["kitchen", "bedroom", "garage", "hallway"], 0)], "text"),
    row("t03", None, "The team meeting was moved from Tuesday to Thursday afternoon.",
        [q("Which day is the meeting now?", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 3)], "text"),
    row("t04", None, "The package weighs twelve kilograms and must arrive by tomorrow morning.",
        [q("How urgent is the delivery?", ["low", "medium", "high"], 2), q("Is the package light?", NO_YES, 0)], "text"),
    row("t05", None, "The printer on the second floor shows a paper jam error. Its ink and toner levels are full.",
        [q("What is the problem with the printer?", ["paper jam", "no ink", "network error", "power failure", "driver crash", "overheating", "low toner"], 0)], "text"),
    row("t06", None, "Set an alarm for 6:30 tomorrow and turn off the bedroom lights.",
        [q("What is the first requested action?", ["set an alarm", "play music", "call someone", "turn off the lights"], 0),
         q("Which room is mentioned?", ["kitchen", "bedroom", "garage"], 1)], "text"),
]


def check_rows(rows):
    ids = [r["id"] for r in rows]
    assert len(ids) == len(set(ids)), "duplicate row id"
    for r in rows:
        assert r["image"] is None or r["image"] in IMAGES, r
        text = r["context"] + " ".join(qq["text"] + " " + " ".join(qq["options"]) for qq in r["questions"])
        # A state quoting "Answer" would let the checkpoint's slot finder and GitHub main's disagree.
        assert "Answer" not in text, r["id"]
    counts = sorted({len(qq["options"]) for r in rows for qq in r["questions"]})
    assert counts == list(range(2, 11)), counts


def write_if_changed(path: Path, data: bytes) -> bool:
    """Replace `path` atomically and only when its bytes change, so a reader never sees a partial file."""
    if path.exists() and path.read_bytes() == data:
        return False
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_bytes(data)
    os.replace(tmp, path)
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out-dir", default=str(work_path("_decider2bv", "fixtures")))
    args = ap.parse_args()
    out = Path(args.out_dir).expanduser()
    (out / "images").mkdir(parents=True, exist_ok=True)
    check_rows(ROWS)

    meta, changed = [], []
    for name, (fn, kw) in IMAGES.items():
        im = fn(**kw)
        assert im.mode == "RGB"
        path = out / "images" / f"{name}.png"
        buf = io.BytesIO()
        im.save(buf, format="PNG")
        png = buf.getvalue()
        assert Image.open(io.BytesIO(png)).convert("RGB").tobytes() == im.tobytes(), name  # lossless round trip
        if write_if_changed(path, png):
            changed.append(path.name)
        meta.append({
            "name": name, "path": f"images/{name}.png", "size": list(im.size),
            "sha256": hashlib.sha256(png).hexdigest(),
            "rgb_sha256": hashlib.sha256(im.tobytes()).hexdigest(),
            "generator": {"script": "conversion/decider_vision/make_fixture_images.py", "function": fn.__name__, "args": kw},
            "license": LICENSE,
        })
    for name, obj in (("meta.json", {"license": LICENSE, "images": meta}), ("rows.json", {"rows": ROWS})):
        if write_if_changed(out / name, (json.dumps(obj, indent=1, ensure_ascii=False) + "\n").encode()):
            changed.append(name)
    n_slots = sum(len(r["questions"]) for r in ROWS)
    n_multi = sum(len(r["questions"]) > 1 for r in ROWS)
    n_text = sum(r["image"] is None for r in ROWS)
    print(f"{len(meta)} images, {len(ROWS)} rows ({n_text} text-only, {n_multi} multi-question), {n_slots} slots -> {out}")
    print(f"files rewritten: {changed if changed else 'none (all byte-identical)'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
