#!/usr/bin/env python3
"""Fixture pictures + image records for the d1-3B vision path, drawn from nothing.

Every picture is generated here with Pillow's drawing primitives (rectangles, ellipses, polygons, lines, flat and
graded fills) from a fixed seed; no photo, font or downloaded asset is involved, there is no text in any picture, and
nothing real is depicted, so the pictures are published under CC0-1.0. The twelve sizes cover the processor's paths
(`vision_host.py` section 2): one crop at native aspect (384x384, 384x256, 256x384, 640x480, 480x640, 300x300),
512-px tiles + thumbnail (1024x768, 768x1024, 1024x1024), a wide picture that stays one crop (1200x400) and the provider's 1-megapixel cap
before the tiles (1600x1200, 2048x1536).

Every record is `{id, source, request: {state, questions: {qid: {type, instructions, criteria}}}, images: [path],
gold: {qid: key}, note}`: `request` is the arguments of d1's `model.system_one(state, questions, images=...)`, the
gold keys follow `make_fixtures.py` (a criteria name for choice, "true" / "false" for noul, the level index as a
string for score) and come from what was drawn (`drawn` in meta.json):

    count    choice  "How many shapes are in the picture?"  one / two / three / four_or_more
    largest  choice  "What color is the largest shape?"     red / orange / yellow / green / blue / purple
    circle   noul    "Is there a circle in the picture?"
    crowded  score   "How crowded is the picture?"          0 Nearly empty (1-2 shapes) / 1 A few shapes (3-8)
                                                            / 2 Packed with shapes (9+)

A shape is a saturated circle, square / rectangle or triangle; bands, gradients and lattice lines are background. The
largest shape (by drawn area) is at least 1.4x the next one of another color.

`card_cats` is the model card's image example (README.md of LiquidAI/d1-3B @ da1fe36a): its request as printed and the
COCO URL it loads. The picture is NOT fetched or stored by this file: the record is for a measurement only and is not
part of the published fixture (a third-party photo).

    python make_fixture_images.py     # -> $ZOO_WORK_ROOT/_d1_3b/fixtures/{images/*.png, images/meta.json, image_records.json}

Two more sets for the Swift host's pixel gate (`gate_swift_pixels.py`); neither adds a record:

    --random   images_random/random_<w>x<h>.png: the six random pictures test_vision_host.py draws (NumPy
               default_rng(0), rng.integers(0, 256, (h, w, 3), uint8) in RANDOM_SIZES order), stored losslessly
    --exif     images_exif/<id>_rot90_o6.jpg: a drawn picture turned 90 degrees clockwise and saved as a JPEG (Pillow,
               quality 95) whose EXIF Orientation is 6, so a reader that applies the tag turns it another 90 degrees
               clockwise (the card's `load_image` = `ImageOps.exif_transpose` then `convert("RGB")`: img01 rotated
               180 degrees); <id>_rot90_o6.png = exactly those decoded and transposed pixels, lossless, no EXIF, to
               tell a decoder's difference from an orientation error. img01 (384x384, the pair the launch names) is
               square, so its crop plan cannot show a wrong orientation; img04 (640x480 -> stored 480x640) can.

The drawing is deterministic: a re-run reproduces each picture's raw-RGB sha256 (the PNG bytes depend on zlib, the
JPEG bytes on Pillow's libjpeg).
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
import os
import random
import sys
from pathlib import Path

from PIL import Image, ImageDraw

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from _paths import work_path  # noqa: E402

LICENSE = "self-made (generated by conversion/d1/make_fixture_images.py), CC0-1.0"
MODEL = {"hf_id": "LiquidAI/d1-3B", "revision": "da1fe36a861f24690f27f622dca1d8688503d113"}
README_SHA256 = "cf063f71ce852ef4c924d192c34f61727f11d121c60b01ad9092ba93ac03bda3"
CATS_URL = "http://images.cocodataset.org/val2017/000000039769.jpg"

COLORS = {"red": (220, 40, 40), "orange": (240, 140, 20), "yellow": (235, 205, 30),
          "green": (40, 160, 60), "blue": (40, 80, 220), "purple": (130, 50, 170)}
QUESTIONS = {
    "count": {"type": "choice", "instructions": "How many shapes are in the picture?",
              "criteria": {"one": "One", "two": "Two", "three": "Three", "four_or_more": "Four or more"}},
    "largest": {"type": "choice", "instructions": "What color is the largest shape?",
                "criteria": {k: k.capitalize() for k in COLORS}},
    "circle": {"type": "noul", "instructions": "Is there a circle in the picture?"},
    "crowded": {"type": "score", "instructions": "How crowded is the picture?",
                "criteria": ["Nearly empty", "A few shapes", "Packed with shapes"]},
}


# --------------------------------------------------------------------------- drawing
class Canvas:
    """A picture and the shapes on it (kind, color name, area in pixels)."""

    def __init__(self, w: int, h: int, bg=(255, 255, 255)):
        self.im = Image.new("RGB", (w, h), bg)
        self.d = ImageDraw.Draw(self.im)
        self.shapes: list[dict] = []

    def circle(self, cx, cy, r, color):
        self.d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=COLORS[color])
        self.shapes.append({"kind": "circle", "color": color, "area": round(math.pi * r * r)})

    def rect(self, x0, y0, x1, y1, color):
        self.d.rectangle([x0, y0, x1, y1], fill=COLORS[color])
        self.shapes.append({"kind": "square" if x1 - x0 == y1 - y0 else "rectangle", "color": color,
                            "area": (x1 - x0) * (y1 - y0)})

    def triangle(self, cx, cy, base, height, color):
        self.d.polygon([(cx - base / 2, cy + height / 2), (cx + base / 2, cy + height / 2), (cx, cy - height / 2)],
                       fill=COLORS[color])
        self.shapes.append({"kind": "triangle", "color": color, "area": round(base * height / 2)})

    def bands(self, colors, horizontal=True):
        w, h = self.im.size
        n = len(colors)
        for i, c in enumerate(colors):
            if horizontal:
                self.d.rectangle([0, i * h // n, w, (i + 1) * h // n], fill=c)
            else:
                self.d.rectangle([i * w // n, 0, (i + 1) * w // n, h], fill=c)

    def gradient(self, top, bottom):
        w, h = self.im.size
        for y in range(h):
            t = y / max(1, h - 1)
            self.d.line([(0, y), (w, y)], fill=tuple(round(a + (b - a) * t) for a, b in zip(top, bottom)))

    def lattice(self, step, color=(150, 150, 150), width=3):
        w, h = self.im.size
        for x in range(step, w, step):
            self.d.line([(x, 0), (x, h)], fill=color, width=width)
        for y in range(step, h, step):
            self.d.line([(0, y), (w, y)], fill=color, width=width)

    def scatter(self, rng: random.Random, n: int, r_min: int, r_max: int, colors, kinds, keep_out=()):
        """n small shapes at non-overlapping random spots (bounding circles 6 px apart, off `keep_out` discs)."""
        w, h = self.im.size
        placed = list(keep_out)
        for _ in range(n):
            for _try in range(2000):
                r = rng.randint(r_min, r_max)
                cx, cy = rng.randint(r + 4, w - r - 4), rng.randint(r + 4, h - r - 4)
                if all(math.hypot(cx - x, cy - y) > r + q + 6 for x, y, q in placed):
                    break
            else:
                raise RuntimeError("no room for another shape")
            placed.append((cx, cy, r))
            kind, color = rng.choice(kinds), rng.choice(colors)
            if kind == "circle":
                self.circle(cx, cy, r, color)
            elif kind == "square":
                s = round(r * 1.4)
                self.rect(cx - s // 2, cy - s // 2, cx - s // 2 + s, cy - s // 2 + s, color)
            else:
                self.triangle(cx, cy, round(r * 1.8), round(r * 1.6), color)
        return placed


def img01(seed):
    c = Canvas(384, 384)
    c.circle(120, 130, 70, "red")
    c.rect(230, 200, 320, 290, "blue")
    c.triangle(110, 300, 100, 90, "green")
    return c


def img02(seed):
    c = Canvas(384, 256, (228, 228, 228))
    c.circle(192, 128, 100, "orange")
    return c


def img03(seed):
    c = Canvas(256, 384)
    c.bands([(250, 220, 225), (250, 245, 205), (210, 240, 245), (230, 222, 248)])
    c.triangle(128, 110, 150, 130, "purple")
    c.triangle(128, 280, 100, 90, "purple")
    return c


def img04(seed):
    rng = random.Random(seed)
    c = Canvas(640, 480)
    c.rect(400, 250, 590, 440, "blue")
    c.circle(90, 90, 22, "red")
    c.scatter(rng, 17, 14, 24, [k for k in COLORS if k != "blue"], ["circle", "square", "triangle"],
              keep_out=[(495, 345, 140), (90, 90, 22)])
    return c


def img05(seed):
    c = Canvas(480, 640, (225, 242, 228))
    c.rect(150, 70, 330, 250, "yellow")
    c.rect(185, 400, 295, 510, "yellow")
    return c


def img06(seed):
    c = Canvas(1024, 768)
    c.lattice(128, (190, 190, 190), 3)
    c.circle(192, 192, 110, "green")
    c.circle(704, 576, 45, "orange")
    c.rect(400, 130, 500, 230, "blue")
    c.rect(820, 300, 920, 400, "red")
    c.triangle(180, 560, 130, 110, "purple")
    c.triangle(600, 330, 110, 100, "yellow")
    return c


def img07(seed):
    c = Canvas(768, 1024)
    c.circle(384, 330, 250, "yellow")
    c.rect(300, 800, 470, 900, "blue")
    return c


def img08(seed):
    c = Canvas(1024, 1024, (236, 236, 236))
    c.lattice(341, (20, 20, 20), 6)
    c.triangle(512, 512, 240, 210, "red")
    return c


def img09(seed):
    c = Canvas(1600, 1200)
    c.gradient((200, 225, 250), (255, 255, 255))
    c.circle(300, 300, 120, "orange")
    c.circle(1300, 900, 110, "orange")
    c.rect(600, 380, 1000, 780, "purple")
    c.triangle(300, 900, 260, 220, "green")
    c.triangle(1300, 300, 240, 200, "green")
    return c


def img10(seed):
    rng = random.Random(seed)
    c = Canvas(2048, 1536)
    c.circle(1024, 768, 300, "red")
    c.scatter(rng, 30, 40, 70, [k for k in COLORS if k != "red"], ["circle", "square", "triangle"],
              keep_out=[(1024, 768, 300)])
    return c


def img11(seed):
    c = Canvas(1200, 400, (252, 246, 215))
    for cx in (250, 600, 950):
        c.circle(cx, 200, 120, "blue")
    return c


def img12(seed):
    c = Canvas(300, 300)
    c.rect(90, 90, 210, 210, "green")
    return c


# id -> (draw function, seed, state, question ids, note)
IMAGES = {
    "img01_shapes_384x384": (img01, 1, None, ["count", "circle"], "one crop 24x24, native size"),
    "img02_circle_384x256": (img02, 2, "A picture from a shape-sorting exercise.", ["largest", "crowded"],
                             "one crop 16x24, native size"),
    "img03_bands_256x384": (img03, 3, None, ["circle"], "one crop 24x16, background bands"),
    "img04_scatter_640x480": (img04, 4, {"source": "drawing", "sheet": 4}, ["crowded", "circle", "largest"],
                              "one crop 26x36 (the 640x480 shape of the card's COCO example), JSON state"),
    "img05_tall_480x640": (img05, 5, None, ["count"], "one crop 36x26"),
    "img06_grid_1024x768": (img06, 6, "Shapes placed on a grid.", ["count", "largest"],
                            "tiles 2x3 + thumbnail 26x36, lattice background"),
    "img07_portrait_768x1024": (img07, 7, None, ["largest", "circle", "crowded"], "tiles 3x2 + thumbnail 36x26"),
    "img08_square_1024x1024": (img08, 8, None, ["circle", "count"], "tiles 2x2 + thumbnail 32x32"),
    "img09_wide_1600x1200": (img09, 9, "A drawing on a large canvas.", ["largest", "crowded"],
                             "cap_pixels to 1182x886, then tiles 2x3 + thumbnail 26x36"),
    "img10_big_2048x1536": (img10, 10, None, ["crowded", "circle"],
                            "cap_pixels to 1182x886, then tiles 2x3 + thumbnail 26x36"),
    "img11_banner_1200x400": (img11, 11, "A banner.", ["count"],
                              "one crop 18x54 (wide; 384x1216 after rounding is under the tile threshold)"),
    "img12_small_300x300": (img12, 12, None, ["largest", "circle", "crowded"], "one crop 18x18 (300 -> 288)"),
}


def facts(c: Canvas) -> dict:
    shapes = c.shapes
    n = len(shapes)
    by_area = sorted(shapes, key=lambda s: -s["area"])
    other = next((s for s in by_area[1:] if s["color"] != by_area[0]["color"]), None)
    return {"n_shapes": n, "has_circle": any(s["kind"] == "circle" for s in shapes),
            "largest_color": by_area[0]["color"], "largest_area": by_area[0]["area"],
            "next_other_color_area": other["area"] if other else None,
            "crowded_level": 0 if n <= 2 else 1 if n <= 8 else 2,
            "kinds": sorted({s["kind"] for s in shapes}), "colors": sorted({s["color"] for s in shapes})}


def gold_for(qid: str, f: dict) -> str:
    if qid == "count":
        return {1: "one", 2: "two", 3: "three"}.get(f["n_shapes"], "four_or_more")
    if qid == "largest":
        return f["largest_color"]
    if qid == "circle":
        return "true" if f["has_circle"] else "false"
    return str(f["crowded_level"])


def card_cats() -> dict:
    return {
        "id": "card_cats", "source": "card",
        "request": {"state": None, "questions": {"cats": {
            "type": "choice", "instructions": "How many cats are there?",
            "criteria": {"one": "One", "two": "Two", "more": "Three or more"}}}},
        "images": [CATS_URL],
        "gold": {"cats": "two"},
        "note": ("model card example: model.system_one(None, {'cats': cats}, images=[image]); gold from the card's "
                 "comment 'two cats on a sofa'. The picture is NOT fetched or stored: measurement only, never part "
                 "of the published fixture (a third-party photo)."),
        "fetch": False,
        "provenance": {"file": "README.md", "repo": MODEL["hf_id"], "revision": MODEL["revision"],
                       "section": "How to use", "readme_sha256": README_SHA256},
    }


def write_if_changed(path: Path, data: bytes) -> bool:
    """Replace `path` atomically and only when its bytes change."""
    if path.exists() and path.read_bytes() == data:
        return False
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_bytes(data)
    os.replace(tmp, path)
    return True


def write_json(path: Path, obj) -> bool:
    return write_if_changed(path, (json.dumps(obj, indent=1, ensure_ascii=False) + "\n").encode())


# --------------------------------------------------------------------------- --random / --exif
RANDOM_SEED = 0
RANDOM_SIZES = [(384, 384), (384, 256), (640, 480), (1024, 768), (1600, 1200), (2048, 1536)]   # w x h, drawing order
EXIF_SOURCES = ["img01_shapes_384x384", "img04_scatter_640x480"]
EXIF_ORIENTATION = 6
JPEG_QUALITY = 95


def write_random(out: Path) -> list[str]:
    """test_vision_host.py's six random pictures (same generator, seed and order), as PNG."""
    import numpy as np

    d = out / "images_random"
    d.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(RANDOM_SEED)
    meta, changed = [], []
    for w, h in RANDOM_SIZES:
        arr = rng.integers(0, 256, (h, w, 3), dtype=np.uint8)
        name = f"random_{w}x{h}"
        buf = io.BytesIO()
        Image.fromarray(arr).save(buf, format="PNG")
        png = buf.getvalue()
        assert np.array_equal(np.asarray(Image.open(io.BytesIO(png)).convert("RGB")), arr), name   # lossless
        if write_if_changed(d / f"{name}.png", png):
            changed.append(f"{name}.png")
        meta.append({"id": name, "path": f"images_random/{name}.png", "size": [w, h],
                     "sha256": hashlib.sha256(png).hexdigest(), "rgb_sha256": hashlib.sha256(arr.tobytes()).hexdigest(),
                     "generator": {"script": "conversion/d1/make_fixture_images.py --random",
                                   "rng": f"numpy.random.default_rng({RANDOM_SEED})",
                                   "draw": "rng.integers(0, 256, (h, w, 3), dtype=uint8), one call per size in this order",
                                   "same_as": "test_vision_host.py RANDOM_SIZES with --seed 0"},
                     "license": LICENSE})
    if write_json(d / "meta.json", {"license": LICENSE, "generator": "conversion/d1/make_fixture_images.py --random",
                                    "images": meta}):
        changed.append("images_random/meta.json")
    return changed


def write_exif(out: Path) -> list[str]:
    """A drawn picture turned 90 degrees clockwise in a JPEG tagged Orientation 6, and the pixels a reader that
    applies the tag decodes from it (Pillow: `ImageOps.exif_transpose`, `convert("RGB")`), as PNG."""
    from PIL import ImageOps

    d = out / "images_exif"
    d.mkdir(parents=True, exist_ok=True)
    meta, changed = [], []
    for src in EXIF_SOURCES:
        fn, seed = IMAGES[src][0], IMAGES[src][1]
        im = fn(seed).im
        stored = im.transpose(Image.Transpose.ROTATE_270)          # 90 degrees clockwise
        exif = Image.Exif()
        exif[0x0112] = EXIF_ORIENTATION
        buf = io.BytesIO()
        stored.save(buf, format="JPEG", quality=JPEG_QUALITY, exif=exif.tobytes())
        jpg = buf.getvalue()
        name = src.split("_")[0] + "_rot90_o6"
        shown = ImageOps.exif_transpose(Image.open(io.BytesIO(jpg))).convert("RGB")
        buf = io.BytesIO()
        shown.save(buf, format="PNG")
        png = buf.getvalue()
        assert Image.open(io.BytesIO(png)).convert("RGB").tobytes() == shown.tobytes(), name   # lossless
        assert Image.open(io.BytesIO(jpg)).getexif().get(0x0112) == EXIF_ORIENTATION, name
        for ext, data in (("jpg", jpg), ("png", png)):
            if write_if_changed(d / f"{name}.{ext}", data):
                changed.append(f"{name}.{ext}")
        meta.append({"id": name, "jpg": f"images_exif/{name}.jpg", "png": f"images_exif/{name}.png",
                     "source": {"id": src, "size": list(im.size), "rgb_sha256": hashlib.sha256(im.tobytes()).hexdigest()},
                     "stored": {"size": list(stored.size), "transform": "PIL transpose ROTATE_270 (90 degrees clockwise)",
                                "rgb_sha256": hashlib.sha256(stored.tobytes()).hexdigest(),
                                "jpeg": {"quality": JPEG_QUALITY, "exif_orientation": EXIF_ORIENTATION,
                                         "encoder": "Pillow " + Image.__version__ + " defaults otherwise"}},
                     "shown": {"size": list(shown.size),
                               "what": f"{src} rotated 180 degrees (orientation 6 turns the stored picture another "
                                       "90 degrees clockwise), as Pillow decodes the JPEG",
                               "rgb_sha256": hashlib.sha256(shown.tobytes()).hexdigest()},
                     "sha256": {"jpg": hashlib.sha256(jpg).hexdigest(), "png": hashlib.sha256(png).hexdigest()},
                     "license": LICENSE})
    if write_json(d / "meta.json", {"license": LICENSE, "generator": "conversion/d1/make_fixture_images.py --exif",
                                    "reader": "transformers.image_utils.load_image: ImageOps.exif_transpose, then "
                                              "convert('RGB')", "images": meta}):
        changed.append("images_exif/meta.json")
    return changed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out-dir", default=str(work_path("_d1_3b", "fixtures")))
    ap.add_argument("--random", action="store_true", help="also write images_random/ (no records)")
    ap.add_argument("--exif", action="store_true", help="also write images_exif/ (no records)")
    args = ap.parse_args()
    out = Path(args.out_dir).expanduser()
    (out / "images").mkdir(parents=True, exist_ok=True)

    meta, records, changed = [], [], []
    for name, (fn, seed, state, qids, note) in IMAGES.items():
        c = fn(seed)
        im = c.im
        w, h = (int(v) for v in name.rsplit("_", 1)[1].split("x"))
        assert im.mode == "RGB" and im.size == (w, h), (name, im.size)
        f = facts(c)
        if f["next_other_color_area"] is not None:
            assert f["largest_area"] >= 1.4 * f["next_other_color_area"], (name, f)
        buf = io.BytesIO()
        im.save(buf, format="PNG")
        png = buf.getvalue()
        assert Image.open(io.BytesIO(png)).convert("RGB").tobytes() == im.tobytes(), name   # lossless round trip
        if write_if_changed(out / "images" / f"{name}.png", png):
            changed.append(f"{name}.png")
        meta.append({"id": name, "path": f"images/{name}.png", "size": [w, h], "sha256": hashlib.sha256(png).hexdigest(),
                     "rgb_sha256": hashlib.sha256(im.tobytes()).hexdigest(),
                     "generator": {"script": "conversion/d1/make_fixture_images.py", "function": fn.__name__,
                                   "seed": seed},
                     "drawn": {"shapes": c.shapes, **f}, "license": LICENSE})
        records.append({"id": name, "source": "own_image",
                        "request": {"state": state, "questions": {q: QUESTIONS[q] for q in qids}},
                        "images": [f"images/{name}.png"], "gold": {q: gold_for(q, f) for q in qids},
                        "note": f"drawn here ({note}); gold from the drawing (meta.json drawn)"})
    records.append(card_cats())

    n_q = sum(len(r["request"]["questions"]) for r in records if r["source"] == "own_image")
    doc = {
        "schema": "d1-image-fixtures/1", "model": MODEL, "license": LICENSE + " (the own_image pictures and records)",
        "record_format": ("{id, source, request: {state, questions: {qid: {type, instructions, criteria}}}, images: "
                          "[path relative to this file, or a URL that is not fetched], gold: {qid: key}, note}; "
                          "request + images = the arguments of d1's model.system_one(state, questions, images)"),
        "gold_keys": ("choice = criteria name, noul = 'true' / 'false', score = level index as a string "
                      "(make_fixtures.py; host.gold_key maps noul to yes / no)"),
        "records": records,
        "summary": {"own_image": len(IMAGES), "questions": n_q,
                    "by_type": {t: sum(q["type"] == t for r in records if r["source"] == "own_image"
                                       for q in r["request"]["questions"].values()) for t in ("choice", "noul", "score")},
                    "questions_per_record": {str(k): sum(len(r["request"]["questions"]) == k for r in records
                                                         if r["source"] == "own_image") for k in (1, 2, 3)},
                    "card_not_fetched": ["card_cats"]},
    }
    for path, obj in ((out / "images" / "meta.json", {"license": LICENSE, "generator": "conversion/d1/make_fixture_images.py",
                                                       "images": meta}),
                      (out / "image_records.json", doc)):
        if write_json(path, obj):
            changed.append(path.name)
    print(f"{len(meta)} pictures, {len(records)} records ({n_q} questions on own pictures) -> {out}")
    if args.random:
        changed += write_random(out)
        print(f"{len(RANDOM_SIZES)} random pictures -> {out / 'images_random'}")
    if args.exif:
        changed += write_exif(out)
        print(f"{len(EXIF_SOURCES)} JPEG + PNG pairs (EXIF orientation {EXIF_ORIENTATION}) -> {out / 'images_exif'}")
    print(f"files rewritten: {changed if changed else 'none (all byte-identical)'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
