#!/usr/bin/env python3
"""Export pngwn/system-one-qwen3.5-4b-scorer — cc-by-nc-4.0 — as a scalar LanguageBundle.

One entry point downloads and LFS-verifies both pinned snapshots with at most two
connections, invokes the beside CPU merge tool, and exports S=1 Qwen3.5 decode.
Run in the frozen coreai_models 397b337 export environment (Python 3.11.13,
coreai-core 1.0.0b2, coreai-torch 0.4.1, coreai-opt 0.2.1, torch 2.9.0,
transformers 4.57.6, safetensors 0.7.0, huggingface_hub 0.36.2,
numpy 2.3.5, tokenizers 0.22.2, accelerate 1.15.0). Merge uses its separate
transformers 5.17.0 / PEFT 0.21.0 environment: --merge-python selects it;
otherwise uv run --script resolves the merge tool's exact inline pins.

HF_HOME controls the local snapshot cache; unset defaults to OUT/.hf-home.
Intermediate verified receipts and merged weights stay in --work-dir (default
OUT/.work). Final directories are OUT/gpu-pipelined/
system_one_qwen3_5_4b_scorer_decode_{fp16,int8lin}. The input embedding retains
248320 rows; metadata vocabulary width 1 describes only the scalar output.
fp16 is the reference. int8lin quantizes linears per block of 32 while head,
embedding, conv1d and norms remain fp16. Nothing is generated by this scorer.

Example: python export_system_one_scorer_decode_pipelined.py int8lin \
    --out-dir exports --merge-python /path/to/oracle/.venv/bin/python
"""
from __future__ import annotations
import argparse, hashlib, json, os, re, shutil, subprocess, sys, time
from pathlib import Path
HF_ID='pngwn/system-one-qwen3.5-4b-scorer'
REVISION='e6464dce15f013c2ef641593a85cc6afcdaea928'
BASE_ID='Qwen/Qwen3.5-4B-Base'
BASE_REV='1001bb4d826a52d1f399e183466143f4da7b741b'
BASE=f'{BASE_ID}@{BASE_REV}'
LICENSE='cc-by-nc-4.0'
def sha(path):
    with Path(path).open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def dump(path,data):
    path=Path(path);path.parent.mkdir(parents=True,exist_ok=True)
    temporary=path.with_name(path.name+'.tmp')
    temporary.write_text(json.dumps(data,indent=2,allow_nan=False)+'\n');temporary.replace(path)
def download(work):
    from huggingface_hub import HfApi,snapshot_download
    record={'schema':'coreai-scalar-download/1','status':'RUNNING','license':LICENSE,'max_workers':2,'hf_home':os.environ['HF_HOME'],'hf_hub_disable_xet':True,'repositories':{}}
    paths={}
    for label,repo,rev,patterns in [
        ('adapter',HF_ID,REVISION,None),
        ('base',BASE_ID,BASE_REV,['*.safetensors','*.index.json','config.json','*tokenizer*','vocab.json','merges.txt','special_tokens_map.json','chat_template.jinja'])]:
        info=HfApi().model_info(repo,revision=rev,files_metadata=True);assert info.sha==rev
        snapshot=Path(snapshot_download(repo,revision=rev,allow_patterns=patterns,max_workers=2))
        files=[]
        for item in info.siblings:
            path=snapshot/item.rfilename
            if not path.is_file():continue
            digest=sha(path);expected=item.lfs.sha256 if item.lfs else None
            if expected:assert digest==expected,f'LFS SHA-256 mismatch: {path}'
            if item.size is not None:assert path.stat().st_size==item.size
            files.append({'name':item.rfilename,'bytes':path.stat().st_size,'sha256':digest,'lfs_sha256':expected,'lfs_match':digest==expected if expected else None})
        if label=='adapter':assert len(files)==len(info.siblings)
        if label=='base':assert len([f for f in files if f['name'].endswith('.safetensors')and f['lfs_match']])==2
        record['repositories'][label]={'repo':repo,'revision':rev,'path':str(snapshot),'files':files,'bytes':sum(f['bytes']for f in files)}
        paths[label]=snapshot;dump(work/'download.json',record)
        print(f'Verified pinned {label}: {snapshot}',flush=True)
    record['status']='PASS';dump(work/'download.json',record);return paths

def linear_quant_config(dtype: str = "int8") -> dict:
    """Linear int8 per block of 32 with scale-multiply dequantization.
    Embedding, conv1d, norms and the bias-free scalar lm_head remain fp16.
    The quantization configuration is unchanged from the gated round-2 export.
    """
    return {
        "execution_mode": "eager",
        "global_config": {
            "op_state_spec": {
                "weight": {
                    "dtype": dtype,
                    "qscheme": "symmetric_with_clipping",
                    "granularity": {"type": "per_block", "block_size": 32, "axis": 1},
                }
            },
            "op_input_spec": None,
            "op_output_spec": None,
        },
        "module_type_configs": {
            "coreai_models.primitives.macos.sdpa.SDPA": None,
            "coreai_models.primitives.macos.rope.RoPE": None,
            "coreai_models.primitives.macos.rms_norm.RMSNorm": None,
            "coreai_models.primitives.macos.rms_norm.RMSNormPlusOne": None,
            "coreai_models.primitives.macos.rms_norm.RMSNormGated": None,
            "torch.nn.modules.sparse.Embedding": None,
            "torch.nn.modules.conv.Conv1d": None,
        },
        "module_name_configs": {r".*lm_head$": None},
    }

def export_graph(args):
    import torch
    from _bundle import write_bundle_metadata
    from scorer_model import load_scorer_model
    from coreai_models.export._constants import TRACE_KV_CACHE_SEQ_LEN
    from coreai_models.export.macos import _EXTERNALIZE_SPECS, export_to_coreai
    from coreai_models.models.macos.qwen3_5 import DECODE_STATE_NAMES, build_decode_state
    from coreai_models.primitives.macos.cache import KVCache
    DTYPE=torch.float16
    name=f"system_one_qwen3_5_4b_scorer_decode_{args.mode}"
    print(f"loading {args.hf_id} fp16 ...")
    # (a)-(c): flat text config, model.* merged tower, and bias-free scalar score head.
    assert args.hf_id == HF_ID
    model = load_scorer_model(
        args.snapshot, max_context_length=args.max_ctx, target_dtype=DTYPE,
        num_layers=None, record_path=Path(args.work_dir) / f"loader_{args.mode}.json")
    head_weight = model.lm_head.weight.detach().clone()
    model.eval()
    cfg = model.config

    n_lin = 0
    for layer in model.model.layers:
        if not layer.is_full:
            layer.linear_attn.use_loopfree_step = True
            n_lin += 1
    print(f"loop-free single-step enabled on {n_lin} linear layers")

    # Decode trace: S=1 static query, dynamic full-length positions, dynamic KV seq.
    trace_past = 64
    input_ids = torch.randint(1, cfg.vocab_size, (1, 1), dtype=torch.int32)
    position_ids = torch.arange(trace_past + 1, dtype=torch.int32).unsqueeze(0)
    state = build_decode_state(cfg, max_seq_len=TRACE_KV_CACHE_SEQ_LEN, dtype=DTYPE)

    reference_inputs = {
        "input_ids": input_ids,
        "position_ids": position_ids,
        "k_cache": state["k_cache"],
        "v_cache": state["v_cache"],
        "conv_state": state["conv_state"],
        "rec_state": state["rec_state"],
    }
    seq_pos = torch.export.Dim("seq_pos", min=2, max=args.max_ctx - 1)
    k_seq = torch.export.Dim("k_seq", min=TRACE_KV_CACHE_SEQ_LEN, max=args.max_ctx)
    v_seq = torch.export.Dim("v_seq", min=TRACE_KV_CACHE_SEQ_LEN, max=args.max_ctx)
    dynamic_shapes = {
        "input_ids": None,  # static [1, 1] - no scan, no while_loop
        "position_ids": {1: seq_pos},
        "k_cache": {KVCache.seq_len_dim(): k_seq},
        "v_cache": {KVCache.seq_len_dim(): v_seq},
        "conv_state": None,
        "rec_state": None,
    }

    if args.mode == "int8lin":
        from coreai_models.export.compression import quantize_pytorch_model
        cfg_q = linear_quant_config("int8")
        print("quantizing (linear int8 per-block-32, mode=int8lin) ...")
        model = quantize_pytorch_model(
            model, tuple(reference_inputs.values()), dynamic_shapes, cfg_q)

    # (d): int8lin excludes the replaced lm_head by its unchanged module name.
    assert re.fullmatch(r".*lm_head$", "lm_head")
    assert model.lm_head.weight.dtype == DTYPE and model.lm_head.bias is None
    assert torch.equal(model.lm_head.weight, head_weight)

    # The loop-free path never calls the GatedDeltaUpdate composite; externalizing
    # the class would mark the (uncalled) submodules and then fail to find them in
    # the traced program. RMSNorm/SDPA stay fused composites for the GPU delegate.
    specs = [s for s in _EXTERNALIZE_SPECS if s.composite_op_name != "gated_delta_update"]
    print("exporting decode-only graph to Core AI dialect ...")
    prog = export_to_coreai(
        model,
        reference_inputs,
        dynamic_shapes=dynamic_shapes,
        input_names=("input_ids", "position_ids"),
        output_names=("logits",),
        state_names=DECODE_STATE_NAMES,
        externalize_modules=specs,
    )
    print("optimizing ...")
    prog.optimize()

    out_dir = Path(args.out_dir) / "gpu-pipelined" / name
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    import coreai.runtime as rt

    aimodel = out_dir / f"{name}.aimodel"
    print(f"saving {aimodel} ...")
    prog.save_asset(aimodel, rt.AIModelAssetMetadata())

    # (e): runtime logits width is 1; the input embedding retains 248320 rows.
    write_bundle_metadata(out_dir, name, args.hf_id, 1, args.max_ctx, revision=REVISION,
        extra={"decision": {"head": "scalar", "temperature": 1.75, "max_len": 384,
            "layout": "state-question-option", "base": BASE, "license": "cc-by-nc-4.0"}})
    from transformers import AutoTokenizer

    AutoTokenizer.from_pretrained(args.tokenizer_snapshot, local_files_only=True).save_pretrained(out_dir / "tokenizer")
    tokenizer = AutoTokenizer.from_pretrained(out_dir / "tokenizer", local_files_only=True)
    source_tokenizer = AutoTokenizer.from_pretrained(args.tokenizer_snapshot, local_files_only=True)
    assert tokenizer.get_vocab() == source_tokenizer.get_vocab()
    assert len(tokenizer) == len(source_tokenizer) == 248077
    print(f"bundle ready: {out_dir}")
    return out_dir


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('mode',nargs='?',default='int8lin',choices=['fp16','int8lin'])
    ap.add_argument('--out-dir',default='exports')
    ap.add_argument('--work-dir')
    ap.add_argument('--merge-python',help='Python in the separate pinned transformers5/PEFT environment; default uv run --script')
    ap.add_argument('--max-ctx',type=int,default=4096)
    args=ap.parse_args();started=time.monotonic()
    args.out_dir=str(Path(args.out_dir).resolve())
    args.work_dir=str(Path(args.work_dir).resolve()if args.work_dir else Path(args.out_dir)/'.work')
    work=Path(args.work_dir);work.mkdir(parents=True,exist_ok=True)
    os.environ['HF_HUB_DISABLE_XET']='1'
    os.environ.setdefault('HF_HOME',str(Path(args.out_dir)/'.hf-home'))
    Path(os.environ['HF_HOME']).mkdir(parents=True,exist_ok=True)
    for key in ('OMP_NUM_THREADS','MKL_NUM_THREADS','VECLIB_MAXIMUM_THREADS'):os.environ.setdefault(key,'8')
    rec={'schema':'coreai-scalar-export/1','status':'RUNNING','license':LICENSE,'mode':args.mode,'argv':sys.argv,'started_epoch':time.time()}
    dump(work/f'export_{args.mode}.json',rec)
    try:
        paths=download(work)
        merger=Path(__file__).with_name('merge_system_one_scorer.py')
        command=([args.merge_python,str(merger)]if args.merge_python else ['uv','run','--script',str(merger)])
        command+=['--base-snapshot',str(paths['base']),'--adapter-snapshot',str(paths['adapter']),'--out',str(work/'merged'),'--report',str(work/'merge.json')]
        rec['merge_command']=command;dump(work/f'export_{args.mode}.json',rec)
        print('MERGE COMMAND: '+json.dumps(command),flush=True)
        subprocess.run(command,check=True,timeout=3600)
        assert json.loads((work/'merge.json').read_text())['status']=='PASS'
        print('MERGE SUBPROCESS EXITED; export begins',flush=True)
        args.snapshot=str(work/'merged');args.tokenizer_snapshot=str(paths['adapter']);args.hf_id=HF_ID
        out=export_graph(args)
        rec.update(status='PASS',bundle=str(out),wall_seconds=time.monotonic()-started)
    except Exception as exc:
        rec.update(status='FAIL',error=f'{type(exc).__name__}: {exc}',wall_seconds=time.monotonic()-started)
        dump(work/f'export_{args.mode}.json',rec);raise
    dump(work/f'export_{args.mode}.json',rec)
if __name__=='__main__':main()
